cargo-features = ["panic-immediate-abort"]

[package]
name = "ronsole"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.25.1"
glow = "0.18.0"
libc = "0.2"
memmap2 = "0.9.11"
portable-pty = "0.9.0"
arboard = { version = "3.6.1", default-features = false, features = ["wayland-data-control"] }
regex = { version = "1.13.1", default-features = false, features = ["std", "unicode-case"] }
resvg = { version = "0.47.0", default-features = false }
rustc-hash = "2.1.3"
swash = "0.2.9"
tiny-skia = "0.12"
unicode-width = "0.2.2"
vte = { version = "0.15.0", default-features = false, features = ["std"] }
glutin = { version = "0.32.3", default-features = false, features = ["egl", "wayland"] }
raw-window-handle = "0.6.2"
wayland-client = { version = "0.31.14", default-features = false, features = ["system"] }
wayland-cursor = "0.31.14"
wayland-protocols = { version = "0.32.12", default-features = false, features = ["client", "staging", "unstable"] }
xkbcommon-dl = "0.4.2"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 4
strip = true
panic = "abort"
